server:
  port: 8081

spring:
  mail:
    host: smtp.example.com
    port: 587
    username: fabio297@gmail.com
    password: Freitas@1
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver

  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true

  profiles:
    active: "@spring.profiles.active@"