#spring.datasource.url=jdbc:mariadb://localhost:3306/salao_de_beleza
#spring.datasource.username=root
#spring.datasource.password=poo123
#spring.jpa.hibernate.ddl-auto=update
#server.port=8081
server:
port: 9080

spring:
  mail:
    host: smtp.example.com
    port: 587
    username: fabio297@gmail.com
    password: Freitas@1
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
    jpa:
    defer-datasource-initialization: true
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    h2:
    console.enabled: true

  profiles:
    active: dev